### ISSUE TITLE
What's the alternative you choose?

### ISSUE THREAD

**Issue by qrilka** [nikita-volkov/cio#1]
If this package was deprecated what should be used instead of it in your opinion?

**Comment by nikita-volkov** [comment]
There's no direct alternative that I know of. I deprecated the package because I no longer had time to continue the research in that problem area.

For a composable abstraction over concurrency I often use `Concurrently` from the "async" package. It however does not concern itself with thread-pools. But there are several other packages on Hackage, which approach the pool problem in their ways.

**Comment by qrilka** [comment]
Sure, there are.
E.g. `async-pool` also containing `Concurrently`.
